### ISSUE TITLE
Spam URL on http://ccodearchive.net/

### ISSUE THREAD

**Issue by voxik** [rustyrussell/ccan#113] opened 2024-03-27 13:46 UTC
~~~
$ curl http://ccodearchive.net/ | grep visit
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2931    0  2931    0     0  21450      0 --:--:-- --:--:-- --:--:-- 21551
<p>We also have a wiki; feel free to enhance it.<br /><br />To see how graphic codes improve the performance of new <strong><a href="https://www.REDACTEDTONOTPROMOTESPAMMERS.com" target="_blank" title="REDACTEDTONOTPROMOTESPAMMERS">REDACTEDTONOTPROMOTESPAMMERS</a></strong>, REDACTEDTONOTPROMOTESPAMMERS.com<br /></p>
~~~

**Comment by voxik** [comment] 2024-03-27 13:48
In case the site is not used anymore (based on https://lists.ozlabs.org/pipermail/ccan/2022-September/001411.html), then the links should be removed from this repository

**Comment by dgibson** [comment] 2024-06-03 04:01
Yes, they should.  This is a duplicate of bug #100.

**Closed by dgibson** 2024-06-03 04:01 UTC
